package com.trevio.android.util

import androidx.annotation.StringRes
import com.trevio.android.R

/**
 * Country constants for phone number selection and currency auto-selection.
 * Mirrors the Web constants/countries.ts — ~190 countries with dial codes,
 * phone lengths, flags, and default currency mappings.
 */

data class CountryInfo(
    val code: String,
    val dialCode: String,
    val name: String,
    @StringRes val nameResId: Int,
    val flag: String,
    val phoneLength: Int,
    val defaultCurrency: String,
    val defaultTimezone: String
)

object CountryConstants {

    const val DEFAULT_COUNTRY_CODE = "IN"
    const val DEFAULT_TIMEZONE = "Asia/Kolkata"

    val COUNTRY_CODES: List<CountryInfo> = listOf(
        CountryInfo("IN", "+91", "India", R.string.country_in, "🇮🇳", 10, "INR", "Asia/Kolkata"),
        CountryInfo("US", "+1", "United States", R.string.country_us, "🇺🇸", 10, "USD", "America/New_York"),
        CountryInfo("GB", "+44", "United Kingdom", R.string.country_gb, "🇬🇧", 10, "GBP", "Europe/London"),
        CountryInfo("AE", "+971", "United Arab Emirates", R.string.country_ae, "🇦🇪", 9, "AED", "Asia/Dubai"),
        CountryInfo("SG", "+65", "Singapore", R.string.country_sg, "🇸🇬", 8, "SGD", "Asia/Singapore"),
        CountryInfo("AU", "+61", "Australia", R.string.country_au, "🇦🇺", 9, "AUD", "Australia/Sydney"),
        CountryInfo("CA", "+1", "Canada", R.string.country_ca, "🇨🇦", 10, "CAD", "America/Toronto"),
        CountryInfo("JP", "+81", "Japan", R.string.country_jp, "🇯🇵", 10, "JPY", "Asia/Tokyo"),
        CountryInfo("DE", "+49", "Germany", R.string.country_de, "🇩🇪", 10, "EUR", "Europe/Berlin"),
        CountryInfo("FR", "+33", "France", R.string.country_fr, "🇫🇷", 9, "EUR", "Europe/Paris"),
        CountryInfo("SA", "+966", "Saudi Arabia", R.string.country_sa, "🇸🇦", 9, "SAR", "Asia/Riyadh"),
        CountryInfo("PK", "+92", "Pakistan", R.string.country_pk, "🇵🇰", 10, "PKR", "Asia/Karachi"),
        CountryInfo("BD", "+880", "Bangladesh", R.string.country_bd, "🇧🇩", 10, "BDT", "Asia/Dhaka"),
        CountryInfo("LK", "+94", "Sri Lanka", R.string.country_lk, "🇱🇰", 10, "LKR", "Asia/Colombo"),
        CountryInfo("NP", "+977", "Nepal", R.string.country_np, "🇳🇵", 10, "NPR", "Asia/Kathmandu"),
        CountryInfo("ZA", "+27", "South Africa", R.string.country_za, "🇿🇦", 9, "ZAR", "Africa/Johannesburg"),
        CountryInfo("NG", "+234", "Nigeria", R.string.country_ng, "🇳🇬", 10, "NGN", "Africa/Lagos"),
        CountryInfo("KE", "+254", "Kenya", R.string.country_ke, "🇰🇪", 9, "KES", "Africa/Nairobi"),
        CountryInfo("IT", "+39", "Italy", R.string.country_it, "🇮🇹", 10, "EUR", "Europe/Rome"),
        CountryInfo("ES", "+34", "Spain", R.string.country_es, "🇪🇸", 9, "EUR", "Europe/Madrid"),
        CountryInfo("NL", "+31", "Netherlands", R.string.country_nl, "🇳🇱", 9, "EUR", "Europe/Amsterdam"),
        CountryInfo("BE", "+32", "Belgium", R.string.country_be, "🇧🇪", 9, "EUR", "Europe/Brussels"),
        CountryInfo("AT", "+43", "Austria", R.string.country_at, "🇦🇹", 10, "EUR", "Europe/Vienna"),
        CountryInfo("CH", "+41", "Switzerland", R.string.country_ch, "🇨🇭", 9, "CHF", "Europe/Zurich"),
        CountryInfo("SE", "+46", "Sweden", R.string.country_se, "🇸🇪", 9, "SEK", "Europe/Stockholm"),
        CountryInfo("NO", "+47", "Norway", R.string.country_no, "🇳🇴", 8, "NOK", "Europe/Oslo"),
        CountryInfo("DK", "+45", "Denmark", R.string.country_dk, "🇩🇰", 8, "DKK", "Europe/Copenhagen"),
        CountryInfo("FI", "+358", "Finland", R.string.country_fi, "🇫🇮", 9, "EUR", "Europe/Helsinki"),
        CountryInfo("IE", "+353", "Ireland", R.string.country_ie, "🇮🇪", 9, "EUR", "Europe/Dublin"),
        CountryInfo("PT", "+351", "Portugal", R.string.country_pt, "🇵🇹", 9, "EUR", "Europe/Lisbon"),
        CountryInfo("GR", "+30", "Greece", R.string.country_gr, "🇬🇷", 10, "EUR", "Europe/Athens"),
        CountryInfo("PL", "+48", "Poland", R.string.country_pl, "🇵🇱", 9, "PLN", "Europe/Warsaw"),
        CountryInfo("CZ", "+420", "Czech Republic", R.string.country_cz, "🇨🇿", 9, "CZK", "Europe/Prague"),
        CountryInfo("HU", "+36", "Hungary", R.string.country_hu, "🇭🇺", 9, "HUF", "Europe/Budapest"),
        CountryInfo("RO", "+40", "Romania", R.string.country_ro, "🇷🇴", 9, "RON", "Europe/Bucharest"),
        CountryInfo("BG", "+359", "Bulgaria", R.string.country_bg, "🇧🇬", 9, "BGN", "Europe/Sofia"),
        CountryInfo("HR", "+385", "Croatia", R.string.country_hr, "🇭🇷", 9, "EUR", "Europe/Zagreb"),
        CountryInfo("SK", "+421", "Slovakia", R.string.country_sk, "🇸🇰", 9, "EUR", "Europe/Bratislava"),
        CountryInfo("SI", "+386", "Slovenia", R.string.country_si, "🇸🇮", 8, "EUR", "Europe/Ljubljana"),
        CountryInfo("LT", "+370", "Lithuania", R.string.country_lt, "🇱🇹", 8, "EUR", "Europe/Vilnius"),
        CountryInfo("LV", "+371", "Latvia", R.string.country_lv, "🇱🇻", 8, "EUR", "Europe/Riga"),
        CountryInfo("EE", "+372", "Estonia", R.string.country_ee, "🇪🇪", 8, "EUR", "Europe/Tallinn"),
        CountryInfo("IS", "+354", "Iceland", R.string.country_is, "🇮🇸", 7, "ISK", "Atlantic/Reykjavik"),
        CountryInfo("LU", "+352", "Luxembourg", R.string.country_lu, "🇱🇺", 8, "EUR", "Europe/Luxembourg"),
        CountryInfo("MT", "+356", "Malta", R.string.country_mt, "🇲🇹", 8, "EUR", "Europe/Malta"),
        CountryInfo("CY", "+357", "Cyprus", R.string.country_cy, "🇨🇾", 8, "EUR", "Asia/Nicosia"),
        CountryInfo("RU", "+7", "Russia", R.string.country_ru, "🇷🇺", 10, "RUB", "Europe/Moscow"),
        CountryInfo("UA", "+380", "Ukraine", R.string.country_ua, "🇺🇦", 9, "UAH", "Europe/Kyiv"),
        CountryInfo("BY", "+375", "Belarus", R.string.country_by, "🇧🇾", 9, "BYN", "Europe/Minsk"),
        CountryInfo("MD", "+373", "Moldova", R.string.country_md, "🇲🇩", 8, "MDL", "Europe/Chisinau"),
        CountryInfo("RS", "+381", "Serbia", R.string.country_rs, "🇷🇸", 8, "RSD", "Europe/Belgrade"),
        CountryInfo("BA", "+387", "Bosnia and Herzegovina", R.string.country_ba, "🇧🇦", 8, "BAM", "Europe/Sarajevo"),
        CountryInfo("MK", "+389", "North Macedonia", R.string.country_mk, "🇲🇰", 8, "MKD", "Europe/Skopje"),
        CountryInfo("AL", "+355", "Albania", R.string.country_al, "🇦🇱", 9, "ALL", "Europe/Tirane"),
        CountryInfo("ME", "+382", "Montenegro", R.string.country_me, "🇲🇪", 8, "EUR", "Europe/Podgorica"),
        CountryInfo("XK", "+383", "Kosovo", R.string.country_xk, "🇽🇰", 8, "EUR", "Europe/Belgrade"),
        CountryInfo("CN", "+86", "China", R.string.country_cn, "🇨🇳", 11, "CNY", "Asia/Shanghai"),
        CountryInfo("HK", "+852", "Hong Kong", R.string.country_hk, "🇭🇰", 8, "HKD", "Asia/Hong_Kong"),
        CountryInfo("TW", "+886", "Taiwan", R.string.country_tw, "🇹🇼", 9, "TWD", "Asia/Taipei"),
        CountryInfo("KR", "+82", "South Korea", R.string.country_kr, "🇰🇷", 10, "KRW", "Asia/Seoul"),
        CountryInfo("KP", "+850", "North Korea", R.string.country_kp, "🇰🇵", 10, "KPW", "Asia/Pyongyang"),
        CountryInfo("TH", "+66", "Thailand", R.string.country_th, "🇹🇭", 9, "THB", "Asia/Bangkok"),
        CountryInfo("VN", "+84", "Vietnam", R.string.country_vn, "🇻🇳", 9, "VND", "Asia/Ho_Chi_Minh"),
        CountryInfo("MY", "+60", "Malaysia", R.string.country_my, "🇲🇾", 9, "MYR", "Asia/Kuala_Lumpur"),
        CountryInfo("ID", "+62", "Indonesia", R.string.country_id, "🇮🇩", 10, "IDR", "Asia/Jakarta"),
        CountryInfo("PH", "+63", "Philippines", R.string.country_ph, "🇵🇭", 10, "PHP", "Asia/Manila"),
        CountryInfo("BN", "+673", "Brunei", R.string.country_bn, "🇧🇳", 7, "BND", "Asia/Brunei"),
        CountryInfo("KH", "+855", "Cambodia", R.string.country_kh, "🇰🇭", 9, "KHR", "Asia/Phnom_Penh"),
        CountryInfo("LA", "+856", "Laos", R.string.country_la, "🇱🇦", 9, "LAK", "Asia/Vientiane"),
        CountryInfo("MM", "+95", "Myanmar", R.string.country_mm, "🇲🇲", 9, "MMK", "Asia/Yangon"),
        CountryInfo("TL", "+670", "Timor-Leste", R.string.country_tl, "🇹🇱", 8, "USD", "Asia/Dili"),
        CountryInfo("MO", "+853", "Macao", R.string.country_mo, "🇲🇴", 8, "MOP", "Asia/Macau"),
        CountryInfo("AF", "+93", "Afghanistan", R.string.country_af, "🇦🇫", 9, "AFN", "Asia/Kabul"),
        CountryInfo("IR", "+98", "Iran", R.string.country_ir, "🇮🇷", 10, "IRR", "Asia/Tehran"),
        CountryInfo("IQ", "+964", "Iraq", R.string.country_iq, "🇮🇶", 10, "IQD", "Asia/Baghdad"),
        CountryInfo("SY", "+963", "Syria", R.string.country_sy, "🇸🇾", 9, "SYP", "Asia/Damascus"),
        CountryInfo("LB", "+961", "Lebanon", R.string.country_lb, "🇱🇧", 8, "LBP", "Asia/Beirut"),
        CountryInfo("JO", "+962", "Jordan", R.string.country_jo, "🇯🇴", 9, "JOD", "Asia/Amman"),
        CountryInfo("IL", "+972", "Israel", R.string.country_il, "🇮🇱", 9, "ILS", "Asia/Jerusalem"),
        CountryInfo("PS", "+970", "Palestine", R.string.country_ps, "🇵🇸", 9, "ILS", "Asia/Gaza"),
        CountryInfo("YE", "+967", "Yemen", R.string.country_ye, "🇾🇪", 9, "YER", "Asia/Aden"),
        CountryInfo("OM", "+968", "Oman", R.string.country_om, "🇴🇲", 8, "OMR", "Asia/Muscat"),
        CountryInfo("QA", "+974", "Qatar", R.string.country_qa, "🇶🇦", 8, "QAR", "Asia/Qatar"),
        CountryInfo("KW", "+965", "Kuwait", R.string.country_kw, "🇰🇼", 8, "KWD", "Asia/Kuwait"),
        CountryInfo("BH", "+973", "Bahrain", R.string.country_bh, "🇧🇭", 8, "BHD", "Asia/Bahrain"),
        CountryInfo("TR", "+90", "Turkey", R.string.country_tr, "🇹🇷", 10, "TRY", "Europe/Istanbul"),
        CountryInfo("EG", "+20", "Egypt", R.string.country_eg, "🇪🇬", 10, "EGP", "Africa/Cairo"),
        CountryInfo("LY", "+218", "Libya", R.string.country_ly, "🇱🇾", 9, "LYD", "Africa/Tripoli"),
        CountryInfo("TN", "+216", "Tunisia", R.string.country_tn, "🇹🇳", 8, "TND", "Africa/Tunis"),
        CountryInfo("DZ", "+213", "Algeria", R.string.country_dz, "🇩🇿", 9, "DZD", "Africa/Algiers"),
        CountryInfo("MA", "+212", "Morocco", R.string.country_ma, "🇲🇦", 9, "MAD", "Africa/Casablanca"),
        CountryInfo("SD", "+249", "Sudan", R.string.country_sd, "🇸🇩", 9, "SDG", "Africa/Khartoum"),
        CountryInfo("SS", "+211", "South Sudan", R.string.country_ss, "🇸🇸", 9, "SSP", "Africa/Juba"),
        CountryInfo("ET", "+251", "Ethiopia", R.string.country_et, "🇪🇹", 9, "ETB", "Africa/Addis_Ababa"),
        CountryInfo("ER", "+291", "Eritrea", R.string.country_er, "🇪🇷", 7, "ERN", "Africa/Asmara"),
        CountryInfo("DJ", "+253", "Djibouti", R.string.country_dj, "🇩🇯", 8, "DJF", "Africa/Djibouti"),
        CountryInfo("SO", "+252", "Somalia", R.string.country_so, "🇸🇴", 9, "SOS", "Africa/Mogadishu"),
        CountryInfo("TZ", "+255", "Tanzania", R.string.country_tz, "🇹🇿", 9, "TZS", "Africa/Dar_es_Salaam"),
        CountryInfo("UG", "+256", "Uganda", R.string.country_ug, "🇺🇬", 9, "UGX", "Africa/Kampala"),
        CountryInfo("RW", "+250", "Rwanda", R.string.country_rw, "🇷🇼", 9, "RWF", "Africa/Kigali"),
        CountryInfo("BI", "+257", "Burundi", R.string.country_bi, "🇧🇮", 8, "BIF", "Africa/Bujumbura"),
        CountryInfo("MZ", "+258", "Mozambique", R.string.country_mz, "🇲🇿", 9, "MZN", "Africa/Maputo"),
        CountryInfo("ZW", "+263", "Zimbabwe", R.string.country_zw, "🇿🇼", 9, "ZWL", "Africa/Harare"),
        CountryInfo("ZM", "+260", "Zambia", R.string.country_zm, "🇿🇲", 9, "ZMW", "Africa/Lusaka"),
        CountryInfo("MW", "+265", "Malawi", R.string.country_mw, "🇲🇼", 9, "MWK", "Africa/Blantyre"),
        CountryInfo("BW", "+267", "Botswana", R.string.country_bw, "🇧🇼", 8, "BWP", "Africa/Gaborone"),
        CountryInfo("NA", "+264", "Namibia", R.string.country_na, "🇳🇦", 9, "NAD", "Africa/Windhoek"),
        CountryInfo("LS", "+266", "Lesotho", R.string.country_ls, "🇱🇸", 8, "LSL", "Africa/Maseru"),
        CountryInfo("SZ", "+268", "Eswatini", R.string.country_sz, "🇸🇿", 8, "SZL", "Africa/Mbabane"),
        CountryInfo("AO", "+244", "Angola", R.string.country_ao, "🇦🇴", 9, "AOA", "Africa/Luanda"),
        CountryInfo("GH", "+233", "Ghana", R.string.country_gh, "🇬🇭", 9, "GHS", "Africa/Accra"),
        CountryInfo("CI", "+225", "Côte d'Ivoire", R.string.country_ci, "🇨🇮", 10, "XOF", "Africa/Abidjan"),
        CountryInfo("SN", "+221", "Senegal", R.string.country_sn, "🇸🇳", 9, "XOF", "Africa/Dakar"),
        CountryInfo("ML", "+223", "Mali", R.string.country_ml, "🇲🇱", 8, "XOF", "Africa/Bamako"),
        CountryInfo("BF", "+226", "Burkina Faso", R.string.country_bf, "🇧🇫", 8, "XOF", "Africa/Ouagadougou"),
        CountryInfo("NE", "+227", "Niger", R.string.country_ne, "🇳🇪", 8, "XOF", "Africa/Niamey"),
        CountryInfo("BJ", "+229", "Benin", R.string.country_bj, "🇧🇯", 8, "XOF", "Africa/Porto-Novo"),
        CountryInfo("TG", "+228", "Togo", R.string.country_tg, "🇹🇬", 8, "XOF", "Africa/Lome"),
        CountryInfo("GN", "+224", "Guinea", R.string.country_gn, "🇬🇳", 9, "GNF", "Africa/Conakry"),
        CountryInfo("SL", "+232", "Sierra Leone", R.string.country_sl, "🇸🇱", 8, "SLL", "Africa/Freetown"),
        CountryInfo("LR", "+231", "Liberia", R.string.country_lr, "🇱🇷", 9, "LRD", "Africa/Monrovia"),
        CountryInfo("MR", "+222", "Mauritania", R.string.country_mr, "🇲🇷", 8, "MRU", "Africa/Nouakchott"),
        CountryInfo("GM", "+220", "Gambia", R.string.country_gm, "🇬🇲", 7, "GMD", "Africa/Banjul"),
        CountryInfo("CV", "+238", "Cape Verde", R.string.country_cv, "🇨🇻", 7, "CVE", "Atlantic/Cape_Verde"),
        CountryInfo("ST", "+239", "São Tomé and Príncipe", R.string.country_st, "🇸🇹", 7, "STN", "Africa/Sao_Tome"),
        CountryInfo("GW", "+245", "Guinea-Bissau", R.string.country_gw, "🇬🇼", 9, "XOF", "Africa/Bissau"),
        CountryInfo("GQ", "+240", "Equatorial Guinea", R.string.country_gq, "🇬🇶", 9, "XAF", "Africa/Malabo"),
        CountryInfo("GA", "+241", "Gabon", R.string.country_ga, "🇬🇦", 8, "XAF", "Africa/Libreville"),
        CountryInfo("CG", "+242", "Congo", R.string.country_cg, "🇨🇬", 9, "XAF", "Africa/Brazzaville"),
        CountryInfo("CD", "+243", "DR Congo", R.string.country_cd, "🇨🇩", 9, "CDF", "Africa/Kinshasa"),
        CountryInfo("TD", "+235", "Chad", R.string.country_td, "🇹🇩", 8, "XAF", "Africa/Ndjamena"),
        CountryInfo("CF", "+236", "Central African Republic", R.string.country_cf, "🇨🇫", 8, "XAF", "Africa/Bangui"),
        CountryInfo("CM", "+237", "Cameroon", R.string.country_cm, "🇨🇲", 9, "XAF", "Africa/Douala"),
        CountryInfo("KM", "+269", "Comoros", R.string.country_km, "🇰🇲", 7, "KMF", "Indian/Comoro"),
        CountryInfo("MG", "+261", "Madagascar", R.string.country_mg, "🇲🇬", 9, "MGA", "Indian/Antananarivo"),
        CountryInfo("MU", "+230", "Mauritius", R.string.country_mu, "🇲🇺", 8, "MUR", "Indian/Mauritius"),
        CountryInfo("SC", "+248", "Seychelles", R.string.country_sc, "🇸🇨", 7, "SCR", "Indian/Mahe"),
        CountryInfo("BR", "+55", "Brazil", R.string.country_br, "🇧🇷", 11, "BRL", "America/Sao_Paulo"),
        CountryInfo("AR", "+54", "Argentina", R.string.country_ar, "🇦🇷", 10, "ARS", "America/Argentina/Buenos_Aires"),
        CountryInfo("MX", "+52", "Mexico", R.string.country_mx, "🇲🇽", 10, "MXN", "America/Mexico_City"),
        CountryInfo("CO", "+57", "Colombia", R.string.country_co, "🇨🇴", 10, "COP", "America/Bogota"),
        CountryInfo("CL", "+56", "Chile", R.string.country_cl, "🇨🇱", 9, "CLP", "America/Santiago"),
        CountryInfo("PE", "+51", "Peru", R.string.country_pe, "🇵🇪", 9, "PEN", "America/Lima"),
        CountryInfo("VE", "+58", "Venezuela", R.string.country_ve, "🇻🇪", 10, "VES", "America/Caracas"),
        CountryInfo("EC", "+593", "Ecuador", R.string.country_ec, "🇪🇨", 9, "USD", "America/Guayaquil"),
        CountryInfo("BO", "+591", "Bolivia", R.string.country_bo, "🇧🇴", 8, "BOB", "America/La_Paz"),
        CountryInfo("PY", "+595", "Paraguay", R.string.country_py, "🇵🇾", 9, "PYG", "America/Asuncion"),
        CountryInfo("UY", "+598", "Uruguay", R.string.country_uy, "🇺🇾", 8, "UYU", "America/Montevideo"),
        CountryInfo("GY", "+592", "Guyana", R.string.country_gy, "🇬🇾", 7, "GYD", "America/Guyana"),
        CountryInfo("SR", "+597", "Suriname", R.string.country_sr, "🇸🇷", 7, "SRD", "America/Paramaribo"),
        CountryInfo("CR", "+506", "Costa Rica", R.string.country_cr, "🇨🇷", 8, "CRC", "America/Costa_Rica"),
        CountryInfo("PA", "+507", "Panama", R.string.country_pa, "🇵🇦", 8, "USD", "America/Panama"),
        CountryInfo("GT", "+502", "Guatemala", R.string.country_gt, "🇬🇹", 8, "GTQ", "America/Guatemala"),
        CountryInfo("HN", "+504", "Honduras", R.string.country_hn, "🇭🇳", 8, "HNL", "America/Tegucigalpa"),
        CountryInfo("SV", "+503", "El Salvador", R.string.country_sv, "🇸🇻", 8, "USD", "America/El_Salvador"),
        CountryInfo("NI", "+505", "Nicaragua", R.string.country_ni, "🇳🇮", 8, "NIO", "America/Managua"),
        CountryInfo("CU", "+53", "Cuba", R.string.country_cu, "🇨🇺", 8, "CUP", "America/Havana"),
        CountryInfo("DO", "+1", "Dominican Republic", R.string.country_do, "🇩🇴", 10, "DOP", "America/Santo_Domingo"),
        CountryInfo("HT", "+509", "Haiti", R.string.country_ht, "🇭🇹", 8, "HTG", "America/Port-au-Prince"),
        CountryInfo("JM", "+1", "Jamaica", R.string.country_jm, "🇯🇲", 10, "JMD", "America/Jamaica"),
        CountryInfo("TT", "+1", "Trinidad and Tobago", R.string.country_tt, "🇹🇹", 10, "TTD", "America/Port_of_Spain"),
        CountryInfo("BB", "+1", "Barbados", R.string.country_bb, "🇧🇧", 10, "BBD", "America/Barbados"),
        CountryInfo("BS", "+1", "Bahamas", R.string.country_bs, "🇧🇸", 10, "BSD", "America/Nassau"),
        CountryInfo("GD", "+1", "Grenada", R.string.country_gd, "🇬🇩", 10, "XCD", "America/Grenada"),
        CountryInfo("LC", "+1", "Saint Lucia", R.string.country_lc, "🇱🇨", 10, "XCD", "America/St_Lucia"),
        CountryInfo("VC", "+1", "Saint Vincent", R.string.country_vc, "🇻🇨", 10, "XCD", "America/St_Vincent"),
        CountryInfo("AG", "+1", "Antigua and Barbuda", R.string.country_ag, "🇦🇬", 10, "XCD", "America/Antigua"),
        CountryInfo("DM", "+1", "Dominica", R.string.country_dm, "🇩🇲", 10, "XCD", "America/Dominica"),
        CountryInfo("KN", "+1", "Saint Kitts and Nevis", R.string.country_kn, "🇰🇳", 10, "XCD", "America/St_Kitts"),
        CountryInfo("BZ", "+501", "Belize", R.string.country_bz, "🇧🇿", 7, "BZD", "America/Belize"),
        CountryInfo("PR", "+1", "Puerto Rico", R.string.country_pr, "🇵🇷", 10, "USD", "America/Puerto_Rico"),
        CountryInfo("NZ", "+64", "New Zealand", R.string.country_nz, "🇳🇿", 9, "NZD", "Pacific/Auckland"),
        CountryInfo("FJ", "+679", "Fiji", R.string.country_fj, "🇫🇯", 7, "FJD", "Pacific/Fiji"),
        CountryInfo("PG", "+675", "Papua New Guinea", R.string.country_pg, "🇵🇬", 8, "PGK", "Pacific/Port_Moresby"),
        CountryInfo("SB", "+677", "Solomon Islands", R.string.country_sb, "🇸🇧", 7, "SBD", "Pacific/Guadalcanal"),
        CountryInfo("VU", "+678", "Vanuatu", R.string.country_vu, "🇻🇺", 7, "VUV", "Pacific/Efate"),
        CountryInfo("WS", "+685", "Samoa", R.string.country_ws, "🇼🇸", 7, "WST", "Pacific/Apia"),
        CountryInfo("TO", "+676", "Tonga", R.string.country_to, "🇹🇴", 7, "TOP", "Pacific/Tongatapu"),
        CountryInfo("KI", "+686", "Kiribati", R.string.country_ki, "🇰🇮", 5, "AUD", "Pacific/Tarawa"),
        CountryInfo("TV", "+688", "Tuvalu", R.string.country_tv, "🇹🇻", 5, "AUD", "Pacific/Funafuti"),
        CountryInfo("NR", "+674", "Nauru", R.string.country_nr, "🇳🇷", 7, "AUD", "Pacific/Nauru"),
        CountryInfo("PW", "+680", "Palau", R.string.country_pw, "🇵🇼", 7, "USD", "Pacific/Palau"),
        CountryInfo("MH", "+692", "Marshall Islands", R.string.country_mh, "🇲🇭", 7, "USD", "Pacific/Majuro"),
        CountryInfo("FM", "+691", "Micronesia", R.string.country_fm, "🇫🇲", 7, "USD", "Pacific/Pohnpei"),
        CountryInfo("CK", "+682", "Cook Islands", R.string.country_ck, "🇨🇰", 5, "NZD", "Pacific/Rarotonga"),
        CountryInfo("NU", "+683", "Niue", R.string.country_nu, "🇳🇺", 4, "NZD", "Pacific/Niue"),
        CountryInfo("KZ", "+7", "Kazakhstan", R.string.country_kz, "🇰🇿", 10, "KZT", "Asia/Almaty"),
        CountryInfo("UZ", "+998", "Uzbekistan", R.string.country_uz, "🇺🇿", 9, "UZS", "Asia/Tashkent"),
        CountryInfo("TM", "+993", "Turkmenistan", R.string.country_tm, "🇹🇲", 8, "TMT", "Asia/Ashgabat"),
        CountryInfo("KG", "+996", "Kyrgyzstan", R.string.country_kg, "🇰🇬", 9, "KGS", "Asia/Bishkek"),
        CountryInfo("TJ", "+992", "Tajikistan", R.string.country_tj, "🇹🇯", 9, "TJS", "Asia/Dushanbe"),
        CountryInfo("MN", "+976", "Mongolia", R.string.country_mn, "🇲🇳", 8, "MNT", "Asia/Ulaanbaatar"),
        CountryInfo("GE", "+995", "Georgia", R.string.country_ge, "🇬🇪", 9, "GEL", "Asia/Tbilisi"),
        CountryInfo("AM", "+374", "Armenia", R.string.country_am, "🇦🇲", 9, "AMD", "Asia/Yerevan"),
        CountryInfo("AZ", "+994", "Azerbaijan", R.string.country_az, "🇦🇿", 9, "AZN", "Asia/Baku"),
        CountryInfo("BT", "+975", "Bhutan", R.string.country_bt, "🇧🇹", 8, "BTN", "Asia/Thimphu"),
        CountryInfo("MV", "+960", "Maldives", R.string.country_mv, "🇲🇻", 7, "MVR", "Indian/Maldives"),
        CountryInfo("VA", "+39", "Vatican City", R.string.country_va, "🇻🇦", 10, "EUR", "Europe/Vatican"),
        CountryInfo("MC", "+377", "Monaco", R.string.country_mc, "🇲🇨", 8, "EUR", "Europe/Monaco"),
        CountryInfo("SM", "+378", "San Marino", R.string.country_sm, "🇸🇲", 10, "EUR", "Europe/San_Marino"),
        CountryInfo("AD", "+376", "Andorra", R.string.country_ad, "🇦🇩", 6, "EUR", "Europe/Andorra"),
        CountryInfo("LI", "+423", "Liechtenstein", R.string.country_li, "🇱🇮", 7, "CHF", "Europe/Vaduz"),
    )

    /** Look up a country by its ISO-2 code; falls back to the default country */
    fun getCountryByCode(code: String): CountryInfo {
        return COUNTRY_CODES.find { it.code == code } ?: COUNTRY_CODES.first()
    }

    /** Get the default currency for a given country code */
    fun getCurrencyForCountry(countryCode: String): String {
        return getCountryByCode(countryCode).defaultCurrency
    }

    /** Get the default IANA timezone for a given country code */
    fun getTimezoneForCountry(countryCode: String): String {
        return getCountryByCode(countryCode).defaultTimezone
    }

    /** Check if a country code is supported */
    fun isSupportedCountry(code: String): Boolean {
        return COUNTRY_CODES.any { it.code == code }
    }
}
